# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dfeb257fc28c7acaaa6ab6d9ad2cdd1e128e81f8da1bda10e1eb1a6fdb5d5009cf0c09baaa87629d492d4ffe995973babfa7d90e3824c1065762c5da389083b

test:
  secret_key_base: 2a06197f3b038cc7271c6cdd0cdfc25382481a5fc99e8285afb2a86b2e8d2236693cd7a2641e2965ada12aef577fee786ad5f06562978745a6d8a103877adc66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
